# Generated by Django 4.2.7 on 2023-12-11 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_currency_bankaccount_currency_currencyrelation'),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='currency',
            field=models.ForeignKey(default='BYN', on_delete=django.db.models.deletion.CASCADE, to='bank_account.currency'),
            preserve_default=False,
        ),
    ]
