# Generated by Django 4.2.7 on 2023-12-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_card_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_from', to='bank_account.creditcard')),
                ('credit_card_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_to', to='bank_account.creditcard')),
                ('transaction_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactionstatus')),
            ],
            options={
                'ordering': ['-dt'],
            },
        ),
    ]
